### ISSUE TITLE
State Value -> Wrong Type

### ISSUE THREAD

**Issue by Boronsbruder** [iobroker-community-adapters/iobroker.kodi#1]
Following infos are displayed with the new JS-controller:

```
State value to set for "kodi.0.info.audio_channels" has to be type "number" but received type "string"
State value to set for "kodi.0.info.audio_bitrate" has to be type "string" but received type "number"
```

This one only  when restarting the Adapter:
```
State value to set for "kodi.1.info.genre" has to be type "string" but received type "boolean"
```

**Versions:**  
 - Adapter version: v.2.0.7
 - JS-Controller version: v3.3.15

**Comment by Boronsbruder** [comment]
Fixes could be:

change to type number
https://github.com/iobroker-community-adapters/iobroker.kodi/blob/dce1c0688ecdded0b0926595a371763bb474a380/kodi.js#L84



And
https://github.com/iobroker-community-adapters/iobroker.kodi/blob/dce1c0688ecdded0b0926595a371763bb474a380/kodi.js#L468

https://github.com/iobroker-community-adapters/iobroker.kodi/blob/dce1c0688ecdded0b0926595a371763bb474a380/kodi.js#L482

to 
`                    saveState('info.audio_channels', Number (res[0].currentaudiostream.channels));`
and
`                    saveState('info.audio_channels', Number (res[1]['MusicPlayer.Channels']));`

**Comment by Apollon77** [comment]
@Boronsbruder I will look at it soon. Other question: Do you have the adapter installed? Can you check in your node-modules for "kodi-ws" and pack that into a ZIP file and send to me at iobroker@fischer-ka.de ? It seems that the original dev also deleted a used lib and we also need to restore that

**Comment by Apollon77** [comment]
Ok, we have it ...

**Comment by Apollon77** [comment]
Please try GitHub version
