### ISSUE TITLE
Seeking does not work with Kodi >= Matrix

### ISSUE THREAD

**Issue by agross** [iobroker-community-adapters/ioBroker.kodi#13]
**Describe the bug**  

A breaking change in Kodi's API causes seeking with plain numbers to no longer work.

Reference: https://github.com/xbmc/xbmc/pull/15939

In summary: do not call `Player.Seek` with
* `{ "playerid": player_id, "value": parseInt(param) }` 
* but rather `{ "playerid": player_id, "value": { "percentage": parseInt(param) } }`

**Comment by Apollon77** [comment]
since which kodi version this is that way?

**Comment by agross** [comment]
Matrix / 19 according to what I found.

**Comment by agross** [comment]
Unstale

**Comment by mcm1957** [comment]
Keep

**Comment by mcm1957** [comment]
fixed with 3.0.0
