### ISSUE TITLE
 No connection to device or service after update

### ISSUE THREAD

**Issue by cap-blackbeard** [iobroker-community-adapters/ioBroker.kodi#22]
After updating to the current ioBroker version, the kodi adapter generates the following debug log:
   kodi.0 | 2022-12-22 23:26:19.728 | debug | Error: Error: Socket error: Invalid WebSocket frame: invalid UTF-8 sequence
   kodi.0 | 2022-12-22 23:26:19.726 | debug | KODI connecting to: KODI-IP:9090
   kodi.0 | 2022-12-22 23:26:19.726 | debug | Error: Server responded with error: Invalid params.{GetPlayList}
   kodi.0 | 2022-12-22 23:26:19.725 | info | KODI connected

**Versions:**  
 - Adapter version: 2.0.8
 - Node version: v16.19.0
 - Operating system: docker

**Comment by Apollon77** [comment]
Error fixed in 2.0.9 already

**Comment by cap-blackbeard** [comment]
Thanks for the quick help. I installed version 2.0.9 from github and now I get the following log:

kodi.0 | 2022-12-26 23:18:15.514 | debug | Error: SyntaxError: Failed to handle response: Unexpected token � in JSON at position 0
kodi.0 | 2022-12-26 23:18:15.505 | debug | KODI connecting to: 192.168.0.22:9090
kodi.0 | 2022-12-26 23:18:15.505 | debug | Error: Server responded with error: Invalid params.{GetPlayList}
kodi.0 | 2022-12-26 23:18:15.504 | info | KODI connected
